### ISSUE TITLE
FindAndHighlight

### ISSUE THREAD

**Issue by wtang2006** [asposewords/Aspose_Words_NET#2]
I used VS2012 pro to open and run the FindAndHighlight.2010.sln

at line 97 [afterRun.Text = run.Text.Substring(position);], I get this

System.ArgumentOutOfRangeException was unhandled
  Message=startIndex cannot be larger than length of string.
Parameter name: startIndex
  Source=mscorlib
  ParamName=startIndex
  StackTrace:
       at System.String.InternalSubStringWithChecks(Int32 startIndex, Int32 length, Boolean fAlwaysCopy)
       at System.String.Substring(Int32 startIndex)
       at FindAndHighlightExample.Program.SplitRun(Run run, Int32 position) in c:\Users\Administrator.EYEDOC\Documents\GitHub\Aspose_Words_NET\ProgrammingWithDocuments\UsingFindAndReplace\FindAndHighlight\CSharp\Program.cs:line 97
       at FindAndHighlightExample.Program.ReplaceEvaluatorFindAndHighlight.Aspose.Words.IReplacingCallback.Replacing(ReplacingArgs e) in c:\Users\Administrator.EYEDOC\Documents\GitHub\Aspose_Words_NET\ProgrammingWithDocuments\UsingFindAndReplace\FindAndHighlight\CSharp\Program.cs:line 50
       at     . ()
       at Aspose.Words.Range.Replace(Regex pattern, IReplacingCallback handler, Boolean isForward)
       at FindAndHighlightExample.Program.Main() in c:\Users\Administrator.EYEDOC\Documents\GitHub\Aspose_Words_NET\ProgrammingWithDocuments\UsingFindAndReplace\FindAndHighlight\CSharp\Program.cs:line 30
       at System.AppDomain._nExecuteAssembly(Assembly assembly, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by asposewords** [comment]
This issue has been resolved in the latest updates. Please edit RunExamples.cs and un-comment FindAndHighlight.Run() to run the example.
